name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Replace assets path
        uses: jacobtomlinson/gha-find-replace@v0.1.2
        with:
          find: '/assets'
          replace: '/PixelBreaker_WebGPU/assets'
          include: 'dist/index.html'

      - name: Deploy to build branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: ./docs
          keep_files: false
          commit_message: Deploy build to gh-page branch docs directory
